@ECHO OFF
IF %1==BTC GOTO DOBTC
IF %1==MSC GOTO DOMSC
GOTO BATCHERR
:DOBTC
IF %2==LARGE GOTO DOBTCL
IF %2==MEDIUM GOTO DOBTCM
IF %2==SMALL GOTO DOBTCS
GOTO BATCHERR
:DOBTCL
make -DM=l -DS=-ml -DL=tlib -DZ=tcc -DP=-zC -fmakefile.dos
GOTO ENDBATCH
:DOBTCM
make -DM=m -DS=-mm -DL=tlib -DZ=tcc -DP=-zC -fmakefile.dos
GOTO ENDBATCH
:DOBTCS
make -DM=s -DS=-ms -DL=tlib -DZ=tcc -DP=-D -fmakefile.dos
GOTO ENDBATCH
:DOMSC
IF %2==LARGE GOTO DOMSCL
IF %2==MEDIUM GOTO DOMSCM
IF %2==SMALL GOTO DOMSCS
GOTO BATCHERR
:DOMSCL
nmake M=L S=/AL L=LIB X=; Z=QCL P="/NT " makefile.dos
GOTO ENDBATCH
:DOMSCM
nmake M=M S=/AM L=LIB X=; Z=QCL P="/NT " makefile.dos
GOTO ENDBATCH
:DOMSCS
nmake M=S S=/AS L=LIB X=; Z=QCL P="/D" makefile.dos
GOTO ENDBATCH
:BATCHERR
ECHO MUST SPECIFY {COMPILER} {MODEL}
ECHO WHERE {COMPILER} = "MSC" OR "BTC"
ECHO AND {MODEL} = "LARGE", "MEDIUM" OR "SMALL"
ECHO I.E. "MSDOS MSC LARGE" FOR LARGE MICROSOFT LIBRARY
:ENDBATCH

