@ECHO OFF
IF %1==BTC GOTO DOBTC
IF %1==MSC GOTO DOMSC
GOTO BATCHERR
:DOBTC
IF %2==LARGE GOTO DOBTCL
IF %2==MEDIUM GOTO DOBTCM
IF %2==SMALL GOTO DOBTCS
GOTO BATCHERR
:DOBTCL
nmake -DM=l -DS=-ml -DL=tlib -DZ=vcc -DP=-zC -fmakefile.dos
GOTO ENDBATCH
:DOBTCM
nmake -DM=m -DS=-mm -DL=tlib -DZ=vcc -DP=-zC -fmakefile.dos
GOTO ENDBATCH
:DOBTCS
nmake -DM=s -DS=-ms -DL=tlib -DZ=vcc -DP=-D -fmakefile.dos
GOTO ENDBATCH
:DOMSC
IF %2==LARGE GOTO DOMSCL
IF %2==MEDIUM GOTO DOMSCM
IF %2==SMALL GOTO DOMSCS
GOTO BATCHERR
:DOMSCL
nmake -f makefile.dos M=L S=/AL L=LIB X=; Z=QCL P="/NT "
GOTO ENDBATCH
:DOMSCM
nmake -f makefile.dos M=M S=/AM L=LIB X=; Z=QCL P="/NT "
GOTO ENDBATCH
:DOMSCS
nmake -f makefile.dos M=S S=/AS L=LIB X=; Z=QCL P="/D"
GOTO ENDBATCH
:BATCHERR
ECHO MUST SPECIFY {COMPILER} {MODEL}
ECHO WHERE {COMPILER} = "MSC" OR "BTC"
ECHO AND {MODEL} = "LARGE", "MEDIUM" OR "SMALL"
ECHO I.E. "MSDOS MSC LARGE" FOR LARGE MICROSOFT LIBRARY
:ENDBATCH