@@INFORMATION
*
*   Terminal Control Version 1.5
*   Copyright (c) 1985,1986,1987,1988
*   MainStream Software              
*   P.O. Box 64946  
*   Dallas, Texas  75206      
*   (214) 250-3338
*   ALL RIGHTS RESERVED
*   Last Modification: .3 on 5/30/88 at 16:13:16
*
@@ADDRESS
The street address should be entered into this field.  For
example:

14010 Any Rd.
~    Or
~Box 112097

This is an optional entry.

Notice, that if a help screen is too large to fit in
a single window, the help system will pause and wait for a
keypress to continue.
@@DATE
You have two options.  You may leave the date field blank, or
you may enter a valid date.  Unless the date entered is valid
and in the form "MM/DD/YY", the cursor will return to the location
of the first error and you will not be able to advance to the
next field.  Remember, if you enter a date, it MUST be valid.
@@NAME
Pleae enter your first name, a space, and your last name in
this field.  This entry is not used for any particular
purpose other than to demonstrate some of Terminal Control's
powerful features, so please, enter your name here.
@@City
Please enter the city or township in this
space.  This entry should be properly
capitalized and punctuated up to the
standards of the United States Postal
Service.
@@State
Each of the fifty united states has a
unique two letter abbreviation.  Notice
that if you enter lowercase letters,
they are put into uppercase when you hit
return.  This is another use of
validation functions.
@@zip
If you don't know what a Zip Code is,
you REALLY need help.

You might notice that you can only enter
numbers.  This is made possible by a
character by character template called
a "picture" that is used as a reference during
data entry.
@@phone
Like the zip code field, the phone
number field also uses a picture to
format the input.

The parentheses and hyphen are called
"special characters" and are also part
of the picture.  These special characters
are automatically inserted in the proper
place in the field for you.

Notice that you don't have to type them
in or cursor over them.  They make it
easy to format all kinds of data.
@@security code
This field demonstrates that you really
can make each field have any attribute
you want.

You can indicate an "active get" attribute
to use when the cursor is on the field,
and a "non-active get" attribute to use
other times.

The best part of all is...

IT's EASY!
@@cost
To our knowledge, Terminal Control is one of
the few that input numeric data from
right to left the way it's supposed to.

Frankly, we got a bit tired of our
$5000 computers being out done by some
$3 calculators.

Notice that the decimal point key toggles
you from one side of the decimal to the
other for easy edits.
@@DATATYPES
With Terminal Control you can input into
numeric datatypes as well as string. There
can be up to 15 different datatypes and
all can be user defined.

Integer, double, float, short, long, and
character arrays are all supported.
@@OPERATING
Terminal Control runs on MS/PC DOS, XENIX, 
UNIX, and VMS.  With out changes to your
source code.  Powerful, fast and portable
@@USERS
You can input into integers because Terminal 
Control will convert an integer to a character
string edit the string and convert it back
automatically.
@@NO HELP
Sorry, no help information was found for
this context.
